// DOM Elements and App State
const invoke =
  window.__TAURI__?.core?.invoke ||
  window.__TAURI_INTERNALS__?.invoke ||
  window.__TAURI_INVOKE__;

if (!invoke) {
  document.body.innerHTML =
    "<p style='padding:16px'>Tauri invoke API is not available.</p>";
  throw new Error("Tauri invoke API is not available");
}

const els = {
  errorBox: document.getElementById("error-box"),
  errorText: document.getElementById("error-text"),
  errorCloseBtn: document.getElementById("error-close-btn"),
  taskBoard: document.getElementById("task-board"),
  taskList: document.getElementById("task-list"),
  searchInput: document.getElementById("search-input"),
  searchClearBtn: document.getElementById("search-clear-btn"),
  toolbarSort: document.getElementById("toolbar-sort"),
  settingsBtn: document.getElementById("settings-btn"),
  filterBtn: document.getElementById("filter-btn"),
  undoBtn: document.getElementById("undo-btn"),
  newTaskBtn: document.getElementById("new-task-btn"),

  taskModal: document.getElementById("task-modal"),
  taskModalTitle: document.getElementById("task-modal-title"),
  taskModalClose: document.getElementById("task-modal-close"),
  taskModalSave: document.getElementById("task-modal-save"),
  taskModalCancel: document.getElementById("task-modal-cancel"),
  taskModalDelete: document.getElementById("task-modal-delete"),
  taskFormName: document.getElementById("task-form-name"),
  taskFormState: document.getElementById("task-form-state"),
  taskFormPinned: document.getElementById("task-form-pinned"),
  taskFormDescription: document.getElementById("task-form-description"),
  taskFormUrgency: document.getElementById("task-form-urgency"),
  taskFormImportance: document.getElementById("task-form-importance"),
  taskFormDue: document.getElementById("task-form-due"),
  taskFormDueOpen: document.getElementById("task-form-due-open"),
  taskFormDueClear: document.getElementById("task-form-due-clear"),
  taskFormCompleted: document.getElementById("task-form-completed"),
  taskFormCompletedOpen: document.getElementById("task-form-completed-open"),
  taskFormCompletedClear: document.getElementById("task-form-completed-clear"),
  taskFormRecurringToggle: document.getElementById(
    "task-form-recurring-toggle",
  ),
  taskFormRecurringRow: document.getElementById("task-form-recurring-row"),
  taskFormRecurringFrequency: document.getElementById(
    "task-form-recurring-frequency",
  ),
  taskFormRecurringHour: document.getElementById("task-form-recurring-hour"),
  taskFormRecurringMinute: document.getElementById(
    "task-form-recurring-minute",
  ),
  taskFormRecurringCustomBtn: document.getElementById(
    "task-form-recurring-custom-btn",
  ),
  taskFormTagInput: document.getElementById("task-form-tag-input"),
  taskFormTagAdd: document.getElementById("task-form-tag-add"),
  taskFormTagsList: document.getElementById("task-form-tags-list"),
  taskFormQuickTags: document.getElementById("task-form-quick-tags"),
  quickTagsLabel: document.getElementById("quick-tags-label"),
  taskFormTimes: document.getElementById("task-form-times"),

  summaryModal: document.getElementById("summary-modal"),
  summaryTitle: document.getElementById("summary-title"),
  summaryStateRow: document.getElementById("summary-state-row"),
  summaryPriorityRow: document.getElementById("summary-priority-row"),
  summaryDescriptionRow: document.getElementById("summary-description-row"),
  summaryTagsRow: document.getElementById("summary-tags-row"),
  summaryTimesRow: document.getElementById("summary-times-row"),
  summaryCloseBtn: document.getElementById("summary-close-btn"),
  summaryOpenDetailBtn: document.getElementById("summary-open-detail-btn"),
  summaryCloseFooterBtn: document.getElementById("summary-close-footer-btn"),

  settingsModal: document.getElementById("settings-modal"),
  settingsModalClose: document.getElementById("settings-modal-close"),
  settingsTheme: document.getElementById("settings-theme"),
  settingsLanguage: document.getElementById("settings-language"),
  settingsOptionalStates: document.getElementById("settings-optional-states"),
  settingsAutoCompleteParents: document.getElementById(
    "settings-auto-complete-parents",
  ),
  settingsTaskFontSize: document.getElementById("settings-task-font-size"),
  settingsTaskFontSizeValue: document.getElementById(
    "settings-task-font-size-value",
  ),
  settingsThemePath: document.getElementById("settings-theme-path"),
  settingsThemeDefaultPath: document.getElementById(
    "settings-theme-default-path",
  ),
  settingsDataDir: document.getElementById("settings-data-dir"),
  settingsImportBtn: document.getElementById("settings-import-btn"),
  settingsLoadTaskbarBtn: document.getElementById("settings-load-taskbar-btn"),
  settingsSaveBtn: document.getElementById("settings-save-btn"),
  settingsDeleteDataBtn: document.getElementById("settings-delete-data-btn"),
  settingsUiScale: document.getElementById("settings-ui-scale"),
  settingsUiScaleValue: document.getElementById("settings-ui-scale-value"),

  filterModal: document.getElementById("filter-modal"),
  filterModalClose: document.getElementById("filter-modal-close"),
  filterImportanceButtons: document.getElementById("filter-importance-buttons"),
  filterUrgencyButtons: document.getElementById("filter-urgency-buttons"),
  filterStateButtons: document.getElementById("filter-state-buttons"),
  filterPinnedButtons: document.getElementById("filter-pinned-buttons"),
  filterTags: document.getElementById("filter-tags"),
  filterClearBtn: document.getElementById("filter-clear-btn"),
  filterApplyBtn: document.getElementById("filter-apply-btn"),

  timeModal: document.getElementById("time-modal"),
  timeModalTitle: document.getElementById("time-modal-title"),
  timeModalClose: document.getElementById("time-modal-close"),
  timeYear: document.getElementById("time-year"),
  timeMonth: document.getElementById("time-month"),
  timeDay: document.getElementById("time-day"),
  timeHour: document.getElementById("time-hour"),
  timeMinute: document.getElementById("time-minute"),
  timeSuggestTonight: document.getElementById("time-suggest-tonight"),
  timeSuggestNow: document.getElementById("time-suggest-now"),
  timeSuggestPlus15: document.getElementById("time-suggest-plus15"),
  timeSuggestTomorrow: document.getElementById("time-suggest-tomorrow"),
  timeModalSave: document.getElementById("time-modal-save"),
  timeModalCancel: document.getElementById("time-modal-cancel"),
  recurrenceModal: document.getElementById("recurrence-modal"),
  recurrenceModalClose: document.getElementById("recurrence-modal-close"),
  recurrenceEvery: document.getElementById("recurrence-every"),
  recurrenceUnit: document.getElementById("recurrence-unit"),
  recurrenceEndMode: document.getElementById("recurrence-end-mode"),
  recurrenceEndDate: document.getElementById("recurrence-end-date"),
  recurrenceEndCount: document.getElementById("recurrence-end-count"),
  recurrenceModalSave: document.getElementById("recurrence-modal-save"),
  recurrenceModalCancel: document.getElementById("recurrence-modal-cancel"),
  confirmModal: document.getElementById("confirm-modal"),
  confirmTitle: document.getElementById("confirm-title"),
  confirmMessage: document.getElementById("confirm-message"),
  confirmCancelBtn: document.getElementById("confirm-cancel-btn"),
  confirmOkBtn: document.getElementById("confirm-ok-btn"),
  hoverTip: document.getElementById("hover-tip"),
  dragZones: document.getElementById("drag-zones"),
  dragDeleteZone: document.getElementById("drag-delete-zone"),
  dragCancelZone: document.getElementById("drag-cancel-zone"),
};

const app = {
  snapshot: null,
  selectedId: null,
  collapsed: new Set(),
  modalMode: "create",
  modalTaskId: null,
  modalParentId: 0,
  summaryTaskId: null,
  modalTags: [],
  appliedFilter: {
    search: "",
    importance: new Set(),
    urgency: new Set(),
    state: new Set(),
    pinned: new Set(),
    tags: new Set(),
  },
  draftFilter: {
    importance: new Set(),
    urgency: new Set(),
    state: new Set(),
    pinned: new Set(),
    tags: new Set(),
  },
  timeEditingField: null,
  recurrenceEnabled: false,
  recurrenceDraft: null,
  drag: {
    active: false,
    taskId: null,
    sourceLi: null,
    placeholder: null,
    pointerOffsetX: 0,
    pointerOffsetY: 0,
    proposal: null,
    zone: null,
    ghost: null,
    autoScrollTimer: null,
  },
  strings: {},
};
