name = "Dark"
primary_bg = "#191A26"
secondary_bg = "#232434"
tertiary_bg = "#2F3142"
pinned_bg = "#4A3420"
accent_color = "#4A86CF"
highlight_bg = "#5A4AA2"
selection_bg = "#3977B8"
text_primary = "#F3F3FA"
text_secondary = "#B5B7C7"
text_muted = "#7D8092"
menu_bg = "#414457"
tooltip_bg = "#161822"
tag_bg = "#3A3C45"
tag_active_bg = "#666A7E"
input_bg = "#1D1F2B"
todo_color = "#7387BA"
in_progress_color = "#E0AC47"
blocked_color = "#D47272"
completed_color = "#74C787"
archived_color = "#7D8092"
importance_high_stripe = "#DB4B4B"
importance_low_stripe = "#48BF63"
urgency_high_stripe = "#EA8A2B"
urgency_low_stripe = "#6AD3FA"
